name: Deploy Scraper

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml shub
    - name: Deploy to zyte
      working-directory: ./PHASE_1/API_SourceCode/Scraper
      if: github.ref == 'refs/heads/master'
      run: python3 set_up_deployment_variables.py && shub deploy
      env:
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONBODB_PASSWORD: ${{ secrets.MONBODB_PASSWORD }}
        GC_SERVICE_ACC_PRIVATE_KEY_ID: ${{ secrets.GC_SERVICE_ACC_PRIVATE_KEY_ID }}
        GC_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.GC_SERVICE_ACC_PRIVATE_KEY }}
        GC_SERVICE_ACC_CLIENT_EMAIL: ${{ secrets.GC_SERVICE_ACC_CLIENT_EMAIL }}
        GC_SERVICE_ACC_CLIENT_ID: ${{ secrets.GC_SERVICE_ACC_CLIENT_ID }}
        ZYTE_API_KEY: ${{ secrets.ZYTE_API_KEY }}