# This is the .github/workflows/main.yml

name: Deploy # Name of the workflow

# Events that trigger a workflow:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: 
  # Only deploys when PR is closed on main branch
  pull_request_target:
    types:
      - closed

jobs:
  # Check out the following article for more inspiration on setting up a
  # standard CI/CD pipeline for most Python projects:
  # https://jarmos.netlify.app/posts/a-standard-ci-cd-pipeline-for-python-projects/
  #test:
  # Include your test suite here.
  #lint:
  # Lint & format your code over here.
  deploy:
    # If the test & lint jobs don't pass,
    # the deploy job willn't even execute
    #needs: [test, lint]
    # Only runs if closed PR is merged into main
    if: github.event.pull_request_target.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploying to Heroku
        # More details available at:
        # https://github.com/akhileshns/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "PHASE_1/API_SourceCode"
          heroku_api_key: "4ede6c72-e042-4982-b21c-3479fd07e4cc"
          heroku_app_name: "seng3011-bobby-tables-backend"
          heroku_email: "cooperbar@gmail.com"
          healthcheck: "https://seng3011-bobby-tables-backend.herokuapp.com/healthcheck"
          rollbackonhealthcheckfailed: true
